export const puzzle = {
  title: "A Little Us",
  rows: [
    "####M####CBD##########",
    "####O#D###E###########",
    "####V#U###D###########",
    "#STAIRCOUNT###########",
    "####E#K###I##T##D###H#",
    "##U#####M#M##H#COFFEE#",
    "##BRICKLANE##R##R###A#",
    "##E#####Y#D##E##R###R#",
    "##R####STORYTELLING#T#",
    "##E#####W#I#####T##G##",
    "#MANGOGREENTEA#JORDANA",
    "##T#E###N#K########L#S",
    "####T###T#########MAFS",
    "####R###Y#S########X##",
    "##J#I###ICK#POT####Y##",
    "##U#L###T#U#L#########",
    "BOBBER##HINGE#########",
    "##E#D#####K#X#########",
    "##L###################",
  ],
  clues: {
    across: {
      2: "In the can before bed",
      5: "Bad Knolly's small-talk topics",
      11: "Worst Edinburgh export",
      12: "First date location",
      13: "Harrison wanted to get better at this on first date",
      15: "Harrison's bubble tea order",
      17: "Name in my phone",
      19: "Hopefully later we watch",
      22: "What I don't give",
      23: "A goey dessert comes in a",
      24: "The child she made for me",
      25: "How we first opened up",
    },
    down: {
      1: "Thing to do today",
      3: "Second best thing for before bed",
      4: "The best kind of runner",
      6: "Perfect amount of dogs",
      7: "Thing make me throw up",
      8: "I ____ my bf",
      9: "Favorite thing for dinner",
      10: "Anniversary",
      14: "Other thing make me throw up",
      16: "Best thing for before bed",
      18: "Wotty",
      20: "A swedish gift",
      21: "Best beer",
      23: "Thanks for watching",
    }
  }
};
